import sys

def exception(errorMessage, cond):
    if(cond): sys.exit(errorMessage)

